### PR TITLE
Purescript 0.12

### PR DESCRIPTION
**Pull request by safareli**

### CODE REVIEW

**Comment by matthewleon** [comment]
Thanks!

**Comment by safareli** [comment]
@matthewleon  can you also make a release?

**Comment by matthewleon** [comment]
@safareli sorry for being very unresponsive here. May I transfer control of this repo to you? I have no interest in maintaining it.

**Comment by safareli** [comment]
> May I transfer control of this repo to you? I have no interest in maintaining it.

@matthewleon yes

**Pull request merged**
